esphome:
  name: comfoair
  platform: ESP8266
  board: esp01_1m

external_components:
  - source:
      type: git
      url: https://github.com/deam0n/esphome-comfoair
      ref: c200
    components: [comfoair]

wifi:
  ssid: 'your-wifi-ssid-here'
  password: 'put-your-wifi-password-here'
    # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Comfoair Fallback Hotspot"
    password: 'put-your-new-ap-password-here'

# Disable uart logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  #password: 'set-an-api-password-here'
  encryption:
    key: 'set-an-api-password-here'
    
ota:

sensor:
binary_sensor:

button:
  - platform: restart
    name: "Comfoair ESP Restart"

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX

comfoair:
  name: "ComfoAir"
  uart_id: uart_bus
  type:
    name: "Type"
  size:
    name: "Size"
  ventilation_level:
    name: "Ventilation level"
  bypass_present:
    name: "Bypass present"
  bypass_valve:
    name: "Bypass valve"
  bypass_valve_open:
    name: "Bypass valve open"
  exhaust_fan_speed:
    name: "Exhaust fan speed"
  return_air_temperature:
    name: "Return air temperature"
  exhaust_air_temperature:
    name: "Exhaust air temperature"
  exhaust_fan_speed_rpm:
    name: "Exhaust fan speed rpm"
  return_air_level:
    name: "Exhaust air level"
  outside_air_temperature:
    name: "Outside air temperature"
  intake_fan_speed:
    name: "Supply fan speed"
  intake_fan_speed_rpm:
    name: "Supply fan speed rpm"
  supply_air_temperature:
    name: "Supply air temperature"
  supply_air_level:
    name: "Supply air level"
  supply_fan_active:
    name: "Supply fan active"
  filter_status:
    name: "Filter status"
  filter_warning_weeks:
    name: "Filter warning weeks"
  bypass_factor:
    name: "Bypass factor"
  bypass_step:
    name: "Bypass step"
  bypass_correction:
    name: "Bypass correction"
  bypass_open_hours:
    name: "Bypass open hours"
  preheating_present:
    name: "Preheating present"
  level0_hours:
    name: "Level 0 hours"
  level1_hours:
    name: "Level 1 hours"
  level2_hours:
    name: "Level 2 hours"
  level3_hours:
    name: "Level 3 hours"
  frost_protection_active:
    name: "Frost protection active"
  frost_protection_hours:
    name: "Frost protection hours"
  frost_protection_minutes:
    name: "Frost protection minutes"
  frost_protection_level:
    name: "Frost protection level"
  filter_hours:
    name: "Filter hours"
  motor_current_bypass:
    name: "Motor current bypass"
  summer_mode:
    name: "Summer mode"
  #preheating_state:
  #  name: "Preheating state"
  #preheating_valve:
  #  name: "Preheating valve"
  #reheating_temperature:
  #  name: "Reheating temperature"
  #preheating_hours:
  #  name: "Preheating hours"
  #motor_current_preheating:
  #  name: "Motor current preheating"
  #kitchen_hood_temperature:
  #  name: "kitchen_hood_temperature"
  #enthalpy_temperature:
  #  name: "enthalpy_temperature"
  #ewt_temperature:
  #  name: "ewt_temperature"
  #enthalpy_present:
  #  name: "enthalpy_present"
  #ewt_present:
  #  name: "ewt_present"
  #options_present:
  #  name: "options_present"
  #p10_active:
  #  name: "p10_active"
  #p11_active:
  #  name: "p11_active"
  #p12_active:
  #  name: "p12_active"
  #p13_active:
  #  name: "p13_active"
  #p14_active:
  #  name: "p14_active"
  #p15_active:
  #  name: "p15_active"
  #p16_active:
  #  name: "p16_active"
  #p17_active:
  #  name: "p17_active"
  #p18_active:
  #  name: "p18_active"
  #p19_active:
  #  name: "p19_active"
  #p90_active:
  #  name: "p90_active"
  #p91_active:
  #  name: "p91_active"
  #p92_active:
  #  name: "p92_active"
  #p93_active:
  #  name: "p93_active"
  #p94_active:
  #  name: "p94_active"
  #p95_active:
  #  name: "p95_active"
  #p96_active:
  #  name: "p96_active"
  #p97_active:
  #  name: "p97_active"
  #bathroom_switch_on_delay_minutes:
  #  name: "bathroom_switch_on_delay_minutes"
  #bathroom_switch_off_delay_minutes:
  #  name: "bathroom_switch_off_delay_minutes"
  #l1_switch_off_delay_minutes:
  #  name: "l1_switch_off_delay_minutes"
  #boost_ventilation_minutes:
  #  name: "boost_ventilation_minutes"
  #rf_high_time_short_minutes:
  #  name: "rf_high_time_short_minutes"
  #rf_high_time_long_minutes:
  #  name: "rf_high_time_long_minutes"
  #extractor_hood_switch_off_delay_minutes:
  #  name: "extractor_hood_switch_off_delay_minutes"
